version: "2"

services:
  jenkins:
      image: jenkins/jenkins:lts
      volumes:
        - "jenkins-data:/var/jenkins_home"
      ports:
        - "8080:8080"
        - "50000:50000"

volumes:
  jenkins-data: {}

networks:
  jenkins:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/24
